### ISSUE TITLE
Glium Demo Lacks depth buffer

### ISSUE THREAD

**Issue by tfinnegan937** [fltk-rs/demos#13]
Hello. Could you please add some code to your glium example showing how to enable the depth buffer? It would be a huuuuuge help to me. I know how to do it in raw OpenGL, but with fltk's glwindow, and then the custom backend, I have no idea how to set it or where to put the code for it. I notice that you've already updated the opengl demo to do so.

A glutin window usually just has the .with_depth_buffer() function which takes the number of bits in the depth buffer as a parameter, but since I'm not using glutin, I'm not sure how to get that functionality with fltk and glium.

**Comment by MoAlyousef** [comment]
Hello
I can't test now, but AFAIR Glium manages state using a public GlState struct. Looking at the docs, it has public fields for depth:
- enabled_depth_test
- depth_range
etc
