### ISSUE TITLE
web-todo demo crashes when clearing pack

### ISSUE THREAD

**Issue by lokxii** [fltk-rs/demos#15]
First I select a number to add things to the pack. Then the pack is populated with stuff. Now I select a number again to add things to the pack, the program crashes with `fatal runtime error: Rust cannot catch foreign exceptions`. The demo does not crash when I remove the line `pack.clear();`

**Comment by MoAlyousef** [comment]
Can you provide more info. I can't get the program to crash on my systems (windows and ubuntu).
