### ISSUE TITLE
Depthbuffer missing on OpenGL example

### ISSUE THREAD

**Issue by yquemener** [fltk-rs/demos#3]
Thanks a lot for these examples, it saved me hours!

I have a small problem on the `opengl/` one. It looks like the openGL context is lacking the depth buffer. Triangles overwrite on each other:

![Screenshot from 2021-05-15 22-21-47](https://user-images.githubusercontent.com/899106/118362813-2b56d980-b5cc-11eb-98b0-51ba52db3ead.png)

I ran the example totally unmodified, latest version, Ubuntu 20.04, just typing `cargo run`.

**Comment by MoAlyousef** [comment]
Thanks for the heads up. I've modified the OpenGL example.
