### ISSUE TITLE
systray high cpu use while no-window no-menu open 

### ISSUE THREAD

**Issue by madaxemad** [fltk-rs/demos#4]
hey 
i lunched systray on windows 10 
it works good but while all windows disappear just icon remains it use around cpu 25% even if you just open menubar it falls but if no window no menu-open around 25% use 

https://user-images.githubusercontent.com/77942735/120110793-502e7d80-c184-11eb-9998-8f5d3a07bcde.MP4

**Comment by madaxemad** [comment]
Hey @MoAlyousef 
would it be nwg problem ?

**Comment by MoAlyousef** [comment]
Hi
I’m not sure. I’ll have to investigate further. And probably update the nwg version as well.

**Comment by MoAlyousef** [comment]
I fixed the example by adding a sleep call when there is no window.
fltk's event loop expects a window and listens for events. Keeping it running without a window while using Window's PeekMessage api causes this.
