### ISSUE TITLE
libvlc demo not working [macos]

### ISSUE THREAD

**Issue by dongjian** [fltk-rs/demos#8]
It works fine on Windows, but not on MAC
![image](https://user-images.githubusercontent.com/2841022/137641052-f2d02041-ff7b-4361-a4ac-06e7e4a59647.png)

vlc version:3.0.8
fltk-rs version:1.2.3

**Comment by MoAlyousef** [comment]
Does this work:
```rust
use fltk::{enums::Color, prelude::*, *};
use vlc::*;

#[derive(Copy, Clone)]
pub enum Message {
    Play,
    Stop,
}

fn main() {
    let app = app::App::default().with_scheme(app::AppScheme::Gtk);
    let mut win = window::Window::new(100, 100, 800, 600, "Media Player");

    // Create inner window to act as embedded media player
    let mut vlc_win = window::Window::new(10, 10, 780, 520, "");
    vlc_win.end();
    vlc_win.set_color(Color::Black);

    let mut but_play = button::Button::new(320, 545, 80, 40, "Play");
    let mut but_stop = button::Button::new(400, 545, 80, 40, "Stop");

    win.end();
    win.show();
    win.make_resizable(true);

    // Take in same args as vlc
    let args: Vec<String> = std::env::args().collect();

    // Instantiate vlc instance and media player
    let instance = Instance::with_args(Some(args)).unwrap();
    let md = Media::new_path(&instance, "video.mp4").unwrap();
    let mdp = MediaPlayer::new(&instance).unwrap();
    mdp.set_media(&md);

    // Get vlc_win handle that we'll pass to libvlc
    // Linux u32, windows HWND, Mac NSWindow
    let handle = vlc_win.raw_handle();

    // Pass the handle to vlc
    // Method depends on the platform
    // For Linux
    #[cfg(target_os = "linux")]
    mdp.set_xwindow(handle as u32);
    // For Windows
    #[cfg(target_os = "windows")]
    mdp.set_hwnd(handle);
    // For MacOS
    #[cfg(target_os = "macos")]
    {
        extern "C" {
            pub fn my_getContentView(xid: *mut raw::c_void) -> *mut raw::c_void;
        }
        mdp.set_nsobject(unsafe { my_getContentView(handle as _) as _ });
    }

    // Disable event handling on vlc's side
    // Do it thru fltk
    mdp.set_key_input(false);
    mdp.set_mouse_input(false);

    let (s, r) = app::channel::<Message>();

    but_play.emit(s, Message::Play);
    but_stop.emit(s, Message::Stop);

    while app.wait() {
        match r.recv() {
            Some(val) => match val {
                Message::Play => mdp.play().unwrap(),
                Message::Stop => mdp.stop(),
            },
            None => (),
        }
    }
}
```

**Comment by dongjian** [comment]
Thank you very much! It's ready to go. Great project!!

**Comment by dongjian** [comment]
Hi MoAlyousef ! I have a strange problem. On the MAC, VLC sometimes only shows a corner of the screen. But sometimes the display is correct. It's perfect on Windows without any problems.  any help?
![image](https://user-images.githubusercontent.com/2841022/141493993-dc26ddc5-82a4-49d2-bda2-29b42ad48443.png)
![image](https://user-images.githubusercontent.com/2841022/141494250-be9dac07-24e8-490d-9392-f982db0bc54e.png)

**Comment by dongjian** [comment]
After some testing, I needed to change the size of vlc_win after the screen was displayed to make the screen look normal(like:vlc_win.set_size(vlc_win.w() - 1, vlc_win.h())) . 
Now I do this to make it work 
```
                    DjVlcMessage::Play => {
                        vlc_win.set_size(vlc_win.w() - 1, vlc_win.h());
                    }
                    DjVlcMessage::Stop => {
                        vlc_win.set_size(vlc_win.w() + 1, vlc_win.h());
                    }
``` 
but the video screen will change in an instant,which can cause some discomfort

**Comment by MoAlyousef** [comment]
I’m not sure. I think it might be this issue in libvlc itself:
https://code.videolan.org/videolan/vlc/-/issues/25264

One thing you can try is to call the wait_for_expose() in the main window after calling ::show()

This might help with the actual pixels_per_unit calculation that libvlc uses for the main window. (Maybe)

**Comment by gowuliao** [comment]
It still does not work on my macos
`
use vlc::*;
use std::os::raw;
use fltk::{enums::Color, prelude::*, *};

#[derive(Copy, Clone)]
pub enum Message {
    Play,
    Stop,
}
       
pub fn run_test() {
    let app = app::App::default().with_scheme(app::AppScheme::Gtk);
    let mut win = window::Window::new(100, 100, 800, 600, "Media Player");

    // Create inner window to act as embedded media player
    let mut vlc_win = window::Window::new(10, 10, 780, 520, "");
    vlc_win.end();
    vlc_win.set_color(Color::Black);

    let mut but_play = button::Button::new(320, 545, 80, 40, "Play");
    let mut but_stop = button::Button::new(400, 545, 80, 40, "Stop");

    win.end();
    win.show();
    win.make_resizable(true);

    // Instantiate vlc instance and media player
    let instance = Instance::new().unwrap();
    let md = Media::new_path(&instance, "~/Downloads/video.mp4").unwrap();
    let mdp = MediaPlayer::new(&instance).unwrap();
    mdp.set_media(&md);

    // Get vlc_win handle that we'll pass to libvlc
    // Linux u32, windows HWND, Mac NSWindow
    let handle = vlc_win.raw_handle();

    // Pass the handle to vlc
    // Method depends on the platform
    // For Linux
    #[cfg(target_os = "linux")]
    mdp.set_xwindow(handle as u32);
    // For Windows
    #[cfg(target_os = "windows")]
    mdp.set_hwnd(handle);
    // For MacOS
    #[cfg(target_os = "macos")]
    {
        extern "C" {
            pub fn my_getContentView(xid: *mut raw::c_void) -> *mut raw::c_void;
        }
        mdp.set_nsobject(unsafe { my_getContentView(handle as _) as _ });
    }

    // Disable event handling on vlc's side
    // Do it thru fltk
    mdp.set_key_input(false);
    mdp.set_mouse_input(false);

    let (s, r) = app::channel::<Message>();

    but_play.emit(s, Message::Play);
    but_stop.emit(s, Message::Stop);

    while app.wait() {
        match r.recv() {
            Some(val) => match val {
                Message::Play => mdp.play().unwrap(),
                Message::Stop => mdp.stop(),
            },
            None => (),
        }
    }
}

`

Error is: 
`
 = note: ld: warning: directory not found for option '-L/demo/test-player/target/debug/build/fltk-sys-c17dafdc9d9e63e8/out/build'
          ld: warning: directory not found for option '-L/demo/test-player/target/debug/build/fltk-sys-c17dafdc9d9e63e8/out/build/Release'
          ld: warning: directory not found for option '-L/demo/test-player/target/debug/build/fltk-sys-c17dafdc9d9e63e8/out/lib64'
          ld: warning: directory not found for option '-L/demo/test-player/target/debug/build/fltk-sys-c17dafdc9d9e63e8/out/lib/Release'
          ld: warning: directory not found for option '-L/demo/test-player/target/debug/build/fltk-sys-c17dafdc9d9e63e8/out/lib64/Release'
          Undefined symbols for architecture x86_64:
            "_my_getContentView", referenced from:
                bt_player::player::run::h80e359bda581f136 in bt_player-30d0b06fe85400ab.55q3uftz9z7yi4dx.rcgu.o
          ld: symbol(s) not found for architecture x86_64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)

`
macos: big sur 11.6.4
vlc 3.0.16
rust: 1.58.1
fltk = "1"
vlc-rs = "0.3"

**Comment by MoAlyousef** [comment]
my_getContentView was replaced with utils::content_view(). 

What’s the output from trying to build the source here:
https://github.com/fltk-rs/demos/blob/master/libvlc/src/main.rs
