### ISSUE TITLE
Two GUI windows appear when run 'mpv' on MacBook Air

### ISSUE THREAD

**Issue by xue35** [fltk-rs/demos#9]
Hi,

There are two GUI windows poped up when I use command `cargo run` to run code 'mpv' on my MacBook Air as screenshot attached. However this won't happen on m Raspberry Pi 400 running debian.
<img width="963" alt="Screen Shot 2022-06-21 at 08 13 46" src="https://user-images.githubusercontent.com/41096224/174691778-62665e9d-9d8d-4305-9560-f44d63104952.png">

Curious what's wrong under the hood.

Cheers,

**Comment by MoAlyousef** [comment]
Hi 

It seems mpv doesn’t support the —wid flag on macos:
https://github.com/mpv-player/mpv/issues/7821

So it just starts its own window. So unfortunately on macos it seems one has to resort to using libmpv (as in the libmpv demo).
